### ISSUE TITLE
merge sh:property shapes of the same prop instance

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#80] opened 2021-07-13 16:43 UTC
owl-shapes-ePO-CM-v2.0.2-2020-11-06.rdf has this (in turtle):
```ttl
epo:Subcontract  a        sh:NodeShape ;
        sh:property       [ a            sh:PropertyShape ;
                            sh:maxCount  1 ;
                            sh:name      "Accepts proposal of" ;
                            sh:path      epo:acceptsProposalOf
                          ] ;
        sh:property       [ a         sh:PropertyShape ;
                            sh:class  epo:AwardDecision ;
                            sh:name   "Accepts proposal of" ;
                            sh:path   epo:acceptsProposalOf
                          ] ;
```
Cannot you merge the two sh:property into one?

**Comment by VladimirAlexiev** [comment] 2021-07-13 17:09
Furthermore, there are sh:property shapes that are totally useless because they don't specify any restriction (and the shapes are not closed):
```ttl
epo:Contract  a           sh:NodeShape ;
        sh:property       [ a        sh:PropertyShape ;
                            sh:name  "Attaches" ;
                            sh:path  epo:attaches
                          ] ;
```

**Comment by costezki** [comment] 2021-07-14 08:18
The separate shapes are generated individually on purpose. This way it is possible to check and specify where the problem is more precisely. 

For example, when we say that at most one AwardDecission shall be provided, the shape may fail for two reasons: (a) more than one is specified or (b) not an AwardDecission. When we split the conditions and check separately, they will fail independently indicating what the problem is. 

Regarding the empty shapes, we need to look at the script and check why they are generated.

**Comment by VladimirAlexiev** [comment] 2021-07-20 10:39
@costezki I think your explanation is wishful thinking. Please show a validation report demonstrating the distinction that you describe.

**Comment by dbd311** [comment] 2022-11-04 08:25
This issue cannot be re-produced since the example withepo:Subcontract  is not searchable in the output.

**Comment by VladimirAlexiev** [comment] 2022-11-06 12:25
@costezki sorry if I was a bit harsh. I say this from practical experience with SHACL engines:
they are not very good at pin-pointing the cause of an error.

Because your sh:PropertyShapes are unnamed (blank nodes), how would your approach help diagnostics?
Please show an example validation report illustrating the two errors for AwardDecision that you give as examples.

@dbd311 You're right, the repos have been reorganized.
But the same problem can be seen eg on 
https://github.com/OP-TED/ePO/blob/master/implementation/ePO/shacl_shapes/ePO_shacl_shapes.rdf#L1726
which describes props of `ContactPoint`

**Comment by costezki** [comment] 2023-06-26 09:07
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.

**Closed as completed by costezki** 2023-06-26 09:07 UTC
Labels: type: feature request
